
theme = "northendlab"
baseURL = "/"
languageCode = "en-us"
title = "Sébastien Le Gall"
metaDataFormat = "yaml"
disqusShortname = "seblegall"


# pygmentsCodeFences = true
# pygmentsUseClasses = true
# pygmentsOptions = "linenos=table,linenostart=1"
# post pagination
paginate = "5"
# post excerpt
summaryLength = "10"

[outputs]
home = ["HTML", "AMP", "RSS", "JSON"]


[markup]
  [markup.highlight]
    codeFences = true
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "github"
    tabWidth = 4

# css plugins
[[params.plugins.css]]
URL = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
URL = "plugins/themify-icons/themify-icons.css"
[[params.plugins.css]]
URL = "css/test.css"

# js plugins
[[params.plugins.js]]
URL = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
URL = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
URL = "plugins/search/fuse.min.js"
[[params.plugins.js]]
URL = "plugins/search/mark.js"
[[params.plugins.js]]
URL = "plugins/search/search.js"

########################### Navigation ###################################

# main menu
[[menu.main]]
URL = "contact"
name = "Contact"
weight = 1

# [[menu.main]]
# URL = "tools"
# name = "tools"
# weight = 2

# footer menu
[[menu.footer]]
URL = "contact"
name = "Contact"
weight = 1

# [[menu.footer]]
# URL = "tools"
# name = "tools"
# weight = 2

######################### Default Parameters ###########################
[params]
# home
home = "Home"
# logo
logo = "images/logo.png"
# meta data
author = "Themefisher"
description = "This is meta description"
# google analitycs ID
googleAnalitycsID = "UA-78265570-1"
# contact form action
contactFormAction = "https://formspree.io/xvogyjrl" # contact form works with : https://formspree.io
# copyright
copyright = "&copy; 2019 Sébastien Le Gall All Rights Reserved"

# preloader
[params.preloader]
enable = true
preloader = "" # use png, jpg, svg or gif format

# search
[params.search]
enable = true

####################### banner #######################################
[params.banner]
bgImage = "images/banner/banner-bg.svg"
title = "Hi, I'm Sébastien Le Gall. <br> I help people build great software together."
image = "images/banner/illustration.svg"


######################## call to action ###############################
[params.cta]
enable = false
image = "images/hugo-muscot.svg"
title = "Get the best hugo templates"
description = "Fusce condimentum nunc ac nisi vulputate fringilla. Donec lacinia congue felis in faucibus."
[params.cta.button]
enable = false
label = "Visit Here"
link = "https://gethugothemes.com/shop/"


############################## Social Site ##########################
# [[params.social]]
# icon = "ti-facebook" # themify icon pack https://themify.me/themify-icons
# link = "#"
[[params.social]]
icon = "ti-twitter-alt" # themify icon pack https://themify.me/themify-icons
link = "https://twitter.com/seb_legall"
[[params.social]]
icon = "ti-github" # themify icon pack https://themify.me/themify-icons
link = "https://github.com/seblegall"
[[params.social]]
icon = "ti-linkedin" # themify icon pack https://themify.me/themify-icons
link = "https://www.linkedin.com/in/sebastienlegall92/"

